name: Kotlin Lint Check

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "LICENSE"
      - ".idea/**"
      - ".github/**"
      - ".editorconfig"
      - "images/**"
      - "metadata/**"

jobs:
  ktlint:
    name: Check Kotlin Code Format
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Run ktlint
        env:
          KTLINT_SHA256: a16be01dcc480aab2f55f444b620142152f66e31564b3b9376506d624c28a2ad
        run: |
          curl --fail --location --silent --show-error --output ktlint "https://github.com/pinterest/ktlint/releases/download/1.5.0/ktlint"
          echo "$KTLINT_SHA256  ktlint" | sha256sum --check --status
          chmod +x ktlint
          ./ktlint "app/src/**/*.kt" "app/src/**/*.kts"
